services:
  llm-lingua-api:
    build: .
    restart: unless-stopped
    image: 'llm-lingua-api'
    container_name: 'llm-lingua-api'
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
